
blank_issues_enabled: false
contact_links:
  - name: Homebridge Slack Channel for Ring
    url: https://homebridgeteam.slack.com/archives/C5N7ZBP7W
    about: For general questions and discussion about homebridge-ring
  - name: Homebridge Reddit
    url: https://www.reddit.com/r/homebridge/
    about: The fastest way to get help and advice from the homebridge community
=======
  - name: Live Stream Issues
    url: https://github.com/dgreif/ring/issues/234
    about: Please Post your live stream issues here.
  - name: Homebridge Slack Channel for Ring
    url: https://homebridgeteam.slack.com/archives/C5N7ZBP7W
    about: Please ask and answer questions here.
  - name: Ring - Pull Requests
    url: https://github.com/dgreif/ring/pulls
    about: Please report security vulnerabilities here.
